##################################################################################
# Safe script runner built in types and plugins definitions.
##################################################################################
plugins:
    safe_script_runner:
        executor: central_deployment_agent
        source: https://github.com/denismakogon/safe-script-runner-plugin/archive/v1.2.0m1.tar.gz
